[config]
baseId = "fhi"
resourceId = ""

[config.aliases]
name = "@base/properties/p-name"
description = "@base/properties/p-description"
employed-by = "@base/properties/p-employed-by"
instance-of = "@base/properties/p-instance-of"
official-website = "@base/properties/p-official-website"
parent-organization = "@base/properties/p-parent-organization"

[n-organization]
name = "Organization"
p-wikidata-id = "Q5510826"

[n-fhi]
name = "The Future of Humanity Institute"
instance-of = "n-organization"
official-website = "http://www.fhi.ox.ac.uk/"
"\employed-by" = [
    "@people/d/h-nick-bostrom",
    "@people/d/h-anders-sandberg",
    "@people/d/h-toby-ord",
    "@people/d/h-owen-cotton-barratt",
    "@people/d/h-joseph-carlsmith",
    "@people/d/h-carl-shulman",
    "@people/d/h-owain-evans",
    "@people/d/h-stuart-armstrong",
    "@people/d/h-ryan-carey",
    "@people/d/h-jelene-luketina",
    "@people/d/h-ozzie-gooen",
]

[n-fhi-leadership]
name = "FHI Leadership Team"
instance-of = "n-organization"
parent-organization = "n-fhi"

[n-fhi-macrostrategy-research-team]
name = "Macrostrategy Research Team"
instance-of = "n-organization"
parent-organization = "n-fhi"

[n-fhi-alexander-tamas-programme]
name = "Alexander Tamas Programme on AI Safety"
instance-of = "n-organization"
parent-organization = "n-fhi"