// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Graph$Reason = require("../src/Graph/Graph.bs.js");

describe("#to_json", (function () {
        return Jest.test("works", (function (param) {
                      var id = Graph$Reason.to_json(Graph$Reason.start);
                      console.log(id);
                      return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](true));
                    }));
      }));

var testData = /* :: */[
  /* tuple */[
    "0",
    "n-george",
    "p-name",
    "George"
  ],
  /* :: */[
    /* tuple */[
      "1",
      "n-cindy",
      "p-name",
      "Cindy"
    ],
    /* :: */[
      /* tuple */[
        "2",
        "p-name",
        "p-name",
        "Name of Item"
      ],
      /* [] */0
    ]
  ]
];

var graph = Graph$Reason.start;

exports.testData = testData;
exports.graph = graph;
/*  Not a pure module */
