[meta.templates.data-type-instance.properties]
p-instance-of = "p-data-type"

[d-thing]
p-name = "Thing (Data Type)"
p-instance-of = "p-data-type"

[d-noun]
p-name = "Noun (Data Type)"
p-instance-of = "p-data-type"

[d-property]
p-name = "Property (Data Type)"
p-instance-of = "p-data-type"

[d-string]
p-name = "String (Data Type)"
p-instance-of = "p-data-type"

[d-url]
p-name = "Url (Data Type)"
p-instance-of = "p-data-type"
p-subclass-of = "d-string"

[d-image-url]
p-name = "Image Url (Data Type)"
p-instance-of = "p-data-type"
p-subclass-of = "d-url"