// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var RList$Rationale = require("rationale/src/RList.js");

var isEqual = Caml_obj.caml_equal;

var isNotEqual = Caml_obj.caml_notequal;

function id(e) {
  return e[/* id */0];
}

function graph(e) {
  return e[/* graph */1];
}

function find(id, t) {
  return RList$Rationale.find((function (e) {
                return e[/* id */0] === id;
              }), t);
}

function to_s(e) {
  return "[ID: " + (e[/* id */0] + "]");
}

var Thing = /* module */[
  /* id */id,
  /* graph */graph,
  /* find */find,
  /* to_s */to_s
];

exports.isEqual = isEqual;
exports.isNotEqual = isNotEqual;
exports.Thing = Thing;
/* RList-Rationale Not a pure module */
