// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Base$Reason = require("./Base.bs.js");
var Fact$Reason = require("./Fact.bs.js");
var RList$Rationale = require("rationale/src/RList.js");
var Function$Rationale = require("rationale/src/Function.js");

function build(fs) {
  var nodes = RList$Rationale.uniq(List.flatten(List.map((function (param) {
                  return /* :: */[
                          param[0],
                          /* :: */[
                            param[1],
                            /* :: */[
                              param[2],
                              /* [] */0
                            ]
                          ]
                        ];
                }), fs)));
  var things = List.map((function (e) {
          return /* record */[
                  /* id */e,
                  /* graph : record */[
                    /* facts : [] */0,
                    /* things : [] */0
                  ]
                ];
        }), nodes);
  var facts = List.map((function (param) {
          return /* record */[
                  /* id */param[0],
                  /* subjectId */param[1],
                  /* propertyId */param[2],
                  /* value */param[3]
                ];
        }), fs);
  var graph = /* record */[
    /* facts */facts,
    /* things */things
  ];
  for(var x = 0 ,x_finish = List.length(things) - 1 | 0; x <= x_finish; ++x){
    List.nth(things, x)[/* graph */1] = graph;
  }
  return graph;
}

function things(g) {
  return g[/* things */1];
}

function facts(g) {
  return g[/* facts */0];
}

function findFact(id) {
  var partial_arg = Fact$Reason.Filters[/* find */1];
  var partial_arg$1 = function (param) {
    return partial_arg(id, param);
  };
  var partial_arg$2 = Function$Rationale.Infix[/* ||> */1];
  return (function (param) {
      return partial_arg$2(facts, partial_arg$1, param);
    });
}

function findThing(id) {
  var partial_arg = Base$Reason.Thing[/* find */2];
  var partial_arg$1 = function (param) {
    return partial_arg(id, param);
  };
  var partial_arg$2 = Function$Rationale.Infix[/* ||> */1];
  return (function (param) {
      return partial_arg$2(things, partial_arg$1, param);
    });
}

function findThingFromFact(g, edge, f) {
  return findThing(Fact$Reason.T[/* edgeId */2](edge)(f))(g);
}

exports.build = build;
exports.things = things;
exports.facts = facts;
exports.findFact = findFact;
exports.findThing = findThing;
exports.findThingFromFact = findThingFromFact;
/* Base-Reason Not a pure module */
