// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var ADT$Reason = require("./Standards/ADT.bs.js");
var ADTToSimple$Reason = require("./Converters/ADTToSimple.bs.js");
var Function$Rationale = require("rationale/src/Function.js");
var SimpleToPrimary$Reason = require("./Converters/SimpleToPrimary.bs.js");
var JsonToUnprocessed$Reason = require("./Converters/JsonToUnprocessed.bs.js");
var UncompressedToAST$Reason = require("./Converters/UncompressedToAST.bs.js");

var partial_arg = Function$Rationale.Infix[/* ||> */1];

function partial_arg$1(param) {
  return partial_arg(JsonToUnprocessed$Reason.run, UncompressedToAST$Reason.run, param);
}

var partial_arg$2 = Function$Rationale.Infix[/* ||> */1];

function partial_arg$3(param) {
  return partial_arg$2(partial_arg$1, ADT$Reason.run, param);
}

var partial_arg$4 = Function$Rationale.Infix[/* ||> */1];

function partial_arg$5(param) {
  return partial_arg$4(partial_arg$3, ADTToSimple$Reason.run, param);
}

var partial_arg$6 = Function$Rationale.Infix[/* ||> */1];

function run(param) {
  return partial_arg$6(partial_arg$5, SimpleToPrimary$Reason.run, param);
}

exports.run = run;
/* ADT-Reason Not a pure module */
