// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function log2(v1, v2) {
  console.log(v1, v2);
  return v2;
}

var isEqual = Caml_obj.caml_equal;

var isNotEqual = Caml_obj.caml_notequal;

exports.log2 = log2;
exports.isEqual = isEqual;
exports.isNotEqual = isNotEqual;
/* No side effect */
