[config]
baseId = "base"
resourceId = "data-types"

[config.aliases]
name = "@base/properties/p-name"
instance-of = "@base/properties/p-instance-of"
subclass-of = "@base/properties/p-subclass-of"

[d-thing]
name = "Thing (Data Type)"
instance-of = "p-data-type"

[d-noun]
name = "Noun (Data Type)"
instance-of = "p-data-type"

[d-property]
name = "Property (Data Type)"
instance-of = "p-data-type"

[d-string]
name = "String (Data Type)"
instance-of = "p-data-type"

[d-url]
name = "Url (Data Type)"
instance-of = "p-data-type"
subclass-of = "d-string"

[d-image-url]
name = "Image Url (Data Type)"
instance-of = "p-data-type"
subclass-of = "d-url"