// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");

var value = Json.parseOrRaise("\n      [\n        {\n        \"baseId\": \"base12\",\n        \"resourceId\": \"2/1\",\n        \"n-fred\": {\n          \"p-name\": \"Fred\",\n          \"p-test\": [\"sdf\", \"sdfsdf\", \"sdfsdf\"],\n          \"p-description\": {\"id\": \"sdf\", \"value\": \"sdffsd\"}\n        }\n      },\n      {\n        \"baseId\": \"base12\",\n        \"resourceId\": \"2/2\",\n        \"n-george\": {\n          \"p-name\": \"George\",\n          \"p-friend\": \"n-jeremy\",\n          \"p-test\": [\"sdf\", \"sdfsdf\", \"sdfsdf\"],\n          \"p-description\": {\"id\": \"sdf\", \"value\": \"sdffsd\"}\n        },\n        \"n-jeremy\": {\n          \"p-name\": \"George\",\n          \"p-test\": [\"sdf\", \"sdfsdf\", \"sdfsdf\"],\n          \"p-description\": {\"id\": \"sdf\", \"value\": \"sdffsd\"}\n        }\n      }]\n   ");

exports.value = value;
/* value Not a pure module */
