// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var testData = /* :: */[
  /* tuple */[
    "g-0",
    "n-george",
    "p-name",
    "George"
  ],
  /* :: */[
    /* tuple */[
      "g-1",
      "n-george",
      "p-description",
      "The person named Goerge"
    ],
    /* :: */[
      /* tuple */[
        "1",
        "n-cindy",
        "p-name",
        "Cindy"
      ],
      /* :: */[
        /* tuple */[
          "2",
          "p-name",
          "p-name",
          "Name of Item"
        ],
        /* :: */[
          /* tuple */[
            "3",
            "p-name",
            "p-description",
            "The name of something"
          ],
          /* :: */[
            /* tuple */[
              "4",
              "2",
              "p-name",
              "The 2nd fact"
            ],
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

exports.testData = testData;
/* No side effect */
