// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Graph_T$BsKen = require("./Graph_T.bs.js");
var RList$Rationale = require("rationale/src/RList.js");
var Function$Rationale = require("rationale/src/Function.js");

function bases(t) {
  return t[/* bases */2];
}

function makeDirs(t) {
  var allThingIdStrings = List.map((function (e) {
          return e[/* thingId */0][/* thingIdString */0];
        }), $$Array.to_list(Js_dict.values(t[/* things */0])));
  var partial_arg = Graph_T$BsKen.Directory[/* allSubdirectories */7];
  var partial_arg$1 = function (param) {
    return List.map(partial_arg, param);
  };
  var partial_arg$2 = List.filter((function (e) {
          return !Graph_T$BsKen.Directory[/* isFactDirectory */6](e);
        }));
  var partial_arg$3 = Graph_T$BsKen.Directory[/* parent */9];
  var partial_arg$4 = function (param) {
    return List.map(partial_arg$3, param);
  };
  var partial_arg$5 = Function$Rationale.Infix[/* ||> */1];
  var partial_arg$6 = function (param) {
    return partial_arg$5(partial_arg$4, partial_arg$2, param);
  };
  var partial_arg$7 = Function$Rationale.Infix[/* ||> */1];
  var partial_arg$8 = function (param) {
    return partial_arg$7(partial_arg$6, partial_arg$1, param);
  };
  var partial_arg$9 = Function$Rationale.Infix[/* ||> */1];
  var partial_arg$10 = function (param) {
    return partial_arg$9(partial_arg$8, List.concat, param);
  };
  var partial_arg$11 = Function$Rationale.Infix[/* ||> */1];
  var possibleUniqueIds = function (param) {
    return partial_arg$11(partial_arg$10, RList$Rationale.uniq, param);
  };
  var directories = Curry._1(possibleUniqueIds, allThingIdStrings);
  return /* record */[
          /* things */t[/* things */0],
          /* facts */t[/* facts */1],
          /* bases */t[/* bases */2],
          /* directories */directories
        ];
}

exports.bases = bases;
exports.makeDirs = makeDirs;
/* Graph_T-BsKen Not a pure module */
