// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Config$BsKen = require("../Config.bs.js");
var Graph_T$BsKen = require("./Graph_T.bs.js");
var Graph_Fact$BsKen = require("./Graph_Fact.bs.js");
var Function$Rationale = require("rationale/src/Function.js");

function findFact(id) {
  var partial_arg = Graph_T$BsKen.F[/* facts */3];
  var partial_arg$1 = Function$Rationale.Infix[/* ||> */1];
  return (function (param) {
      return partial_arg$1(partial_arg, (function (e) {
                    return Js_dict.get(e, id);
                  }), param);
    });
}

function findThing(id, g) {
  return Graph_T$BsKen.F[/* findThing */2](id, g);
}

function findThingFromFact(g, edge, f) {
  var id = Graph_Fact$BsKen.edgeId(edge)(f);
  return Graph_T$BsKen.F[/* findThing */2](id, g);
}

function from_json(param) {
  return Json_decode.list(Graph_Fact$BsKen.from_json, param);
}

function to_json(t) {
  var facts = $$Array.map(Graph_Fact$BsKen.to_json, Js_dict.values(t[/* facts */1]));
  var things = $$Array.map(Graph_T$BsKen.Thing[/* to_json */2], Js_dict.values(t[/* things */0]));
  return Json_encode.object_(/* :: */[
              /* tuple */[
                Config$BsKen.JsonKeys[/* facts */0],
                facts
              ],
              /* :: */[
                /* tuple */[
                  Config$BsKen.JsonKeys[/* things */1],
                  things
                ],
                /* [] */0
              ]
            ]);
}

exports.findFact = findFact;
exports.findThing = findThing;
exports.findThingFromFact = findThingFromFact;
exports.from_json = from_json;
exports.to_json = to_json;
/* Graph_T-BsKen Not a pure module */
