[config]
baseId = "fhi"
resourceId = "_"

[config.aliases]
name = "@base/properties/p-name"
description = "@base/properties/p-description"
employed-by = "@base/properties/p-employed-by"
instance-of = "@base/properties/instance-of"
official-website = "@base/properties/p-official-website"
parent-organization = "@base/properties/p-parent-organization"

[n-organization]
name = "Organization"
p-wikidata-id = "Q5510826"

[n-fhi]
name = "The Future of Humanity Institute"
instance-of = "n-organization"
official-website = "http://www.fhi.ox.ac.uk/"
p-employed-by = [
    "h-nick-bostrom",
    "h-anders-sandberg",
    "h-toby-ord",
    "h-owen-cotton-barratt",
    "h-joseph-carlsmith",
    "h-carl-shulman",
    "h-owain-evans",
    "h-stuart-armstrong",
    "h-ryan-carey",
    "h-jelene-luketina",
    "h-ozzie-gooen",
]

[n-fhi-leadership]
name = "FHI Leadership Team"
instance-of = "n-organization"
parent-organization = "n-fhi"

[n-fhi-macrostrategy-research-team]
name = "Macrostrategy Research Team"
instance-of = "n-organization"
parent-organization = "n-fhi"

[n-fhi-alexander-tamas-programme]
name = "Alexander Tamas Programme on AI Safety"
instance-of = "n-organization"
parent-organization = "n-fhi"