// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Function$Rationale = require("rationale/src/Function.js");
var Compiler_Run$Reason = require("../Compiler/Compiler_Run.bs.js");
var SimpleFactList_ToGraph$Reason = require("../AlternativeGraphFormats/SimpleFactList_ToGraph.bs.js");
var CompressedImporter__ToAST$Reason = require("../Importers/CompressedImporter/CompressedImporter__ToAST.bs.js");
var CompressedImporter__FromJson$Reason = require("../Importers/CompressedImporter/CompressedImporter__FromJson.bs.js");

var partial_arg = Function$Rationale.Infix[/* ||> */1];

function partial_arg$1(param) {
  return partial_arg(CompressedImporter__FromJson$Reason.run, CompressedImporter__ToAST$Reason.run, param);
}

var partial_arg$2 = Function$Rationale.Infix[/* ||> */1];

function partial_arg$3(param) {
  return partial_arg$2(partial_arg$1, Compiler_Run$Reason.run, param);
}

var partial_arg$4 = Function$Rationale.Infix[/* ||> */1];

function partial_arg$5(param) {
  return partial_arg$4(partial_arg$3, Compiler_Run$Reason.toSimple, param);
}

var partial_arg$6 = Function$Rationale.Infix[/* ||> */1];

function run(param) {
  return partial_arg$6(partial_arg$5, SimpleFactList_ToGraph$Reason.run, param);
}

exports.run = run;
/* Compiler_Run-Reason Not a pure module */
