// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Function$Rationale = require("rationale/src/Function.js");
var SimpleFactList_ToGraph$Reason = require("../AlternativeGraphFormats/SimpleFactList_ToGraph.bs.js");
var CompressedImporter__ToAST$Reason = require("../Importers/CompressedImporter/CompressedImporter__ToAST.bs.js");
var CompressedImporter__FromJson$Reason = require("../Importers/CompressedImporter/CompressedImporter__FromJson.bs.js");

var partial_arg = Function$Rationale.Infix[/* ||> */1];

function partial_arg$1(param) {
  return partial_arg(CompressedImporter__FromJson$Reason.run, CompressedImporter__ToAST$Reason.run, param);
}

var partial_arg$2 = Function$Rationale.Infix[/* ||> */1];

function run(param) {
  return partial_arg$2(partial_arg$1, SimpleFactList_ToGraph$Reason.run, param);
}

exports.run = run;
/* SimpleFactList_ToGraph-Reason Not a pure module */
