// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

var isEqual = Caml_obj.caml_equal;

var isNotEqual = Caml_obj.caml_notequal;

function id(e) {
  return e[/* thingId */0][/* thingIdString */0];
}

function find(id, t) {
  return Js_dict.get(t, id);
}

function to_s(e) {
  return "[ID: " + (e[/* thingId */0][/* thingIdString */0] + "]");
}

function to_json(t) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "id",
                t[/* thingId */0][/* thingIdString */0]
              ],
              /* [] */0
            ]);
}

var Thing = /* module */[
  /* id */id,
  /* find */find,
  /* to_s */to_s,
  /* to_json */to_json
];

exports.isEqual = isEqual;
exports.isNotEqual = isNotEqual;
exports.Thing = Thing;
/* No side effect */
