/* Untyped file generated by genType. */

import * as BaseBS from './Base.bs';

export const Thing_to_json = function _(Arg1) { const result = BaseBS.Thing[4]([Arg1.id, [Arg1.graph.facts, Arg1.graph.things]]); return result };
