/* Untyped file generated by genType. */

import * as ConfigBS from './Config.bs';

export const c = function _(Arg1) { const result = ConfigBS.c(Arg1); return {a:result[0], b:result[1]} };

export const updateLatitude = function _(Arg1) { const result = ConfigBS.updateLatitude([Arg1.latitude, Arg1.longitude]); return {latitude:result[0], longitude:result[1]} };
