/* Untyped file generated by genType. */

import * as CreateBucklescriptBlock from 'bs-platform/lib/es6/block.js';

import * as FactBS from './Fact.bs';

export const Query_IS = 0;

export const Query_IS_NOT = 1;

export const Value_to_json = FactBS.Value[0];

export const T_value = FactBS.T[5];

export const T_to_json = FactBS.T[7];

export const Query_fromJson = FactBS.Query[4];

export const Filters_query = FactBS.Filters[0];

export const Filters_withQuery = FactBS.Filters[3];

export const c = FactBS.c;
