/* Untyped file generated by genType. */

import * as FactBS from './Fact.bs';

export const Value_to_json = FactBS.Value[0];

export const T_value = FactBS.T[5];

export const T_to_json = FactBS.T[7];

export const c = FactBS.c;
