/* Untyped file generated by genType. */

import * as Graph_GraphBS from './Graph_Graph.bs';

export const findThing = Graph_GraphBS.findThing;

export const findThingFromFact = Graph_GraphBS.findThingFromFact;

export const to_json = Graph_GraphBS.to_json;
