/* Untyped file generated by genType. */

import * as GraphBS from './Graph.bs';

export const toJs = function _(Arg1) { const result = GraphBS.toJs((Arg1 == null ? undefined : Arg1)); return result };

export const toJs2 = function _(Arg1) { const result = GraphBS.toJs2((Arg1 == null ? undefined : Arg1)); return result };

export const facts = GraphBS.facts;

export const findThing = GraphBS.findThing;

export const findThingFromFact = GraphBS.findThingFromFact;

export const to_json = GraphBS.to_json;

export const load = GraphBS.load;
