/* Untyped file generated by genType. */

import * as Graph_Fact_FiltersBS from './Graph_Fact_Filters.bs';

export const query = Graph_Fact_FiltersBS.query;

export const withQuery = Graph_Fact_FiltersBS.withQuery;
