/* Untyped file generated by genType. */

import * as ThingGBS from './ThingG.bs';

export const isSubjectForFacts = ThingGBS.isSubjectForFacts;

export const isPropertyForFacts = ThingGBS.isPropertyForFacts;

export const isValueForFacts = ThingGBS.isValueForFacts;

export const filterFactsAndSelectThings = ThingGBS.filterFactsAndSelectThings;

export const propertyValues = ThingGBS.propertyValues;
