// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");

Jest.test("first", (function (param) {
        return Jest.Expect[/* toEqual */12](5, Jest.Expect[/* expect */0](5));
      }));

/*  Not a pure module */
