[meta.export]
id = "b-ozzie-personal"

[b-ozzie-personal]
p-name = "Ozzie's main lib"
p-description = "Contains all essential information for ozzie."
p-instance-of = "p-data-source"
p-version = "0.1"

[n-dex]
p-name = "DEX"
p-description = '''
### Description
A organizational tool for structured data with Git.  

### Interesting Links:  
[Specification Links | JSON Schema](http://json-schema.org/specification-links.html)  
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01  
https://tools.ietf.org/html/draft-handrews-json-schema-hyperschema-01  
[GitHub - toml-lang/toml: Tom’s Obvious, Minimal Language](https://github.com/toml-lang/toml)  
[Show HN: Eno – A lightning fast, user-friendly YAML/TOML alternative | Hacker News](https://news.ycombinator.com/item?id=17765426)  
[Online TOML to JSON converter](https://www.randomerrata.com/articles/2013/online-toml-to-json-converter/)  
[Linked data - Wikipedia](https://en.wikipedia.org/wiki/Linked_data)  
[Slowly changing dimension - Wikipedia](https://en.wikipedia.org/wiki/Slowly_changing_dimension)  
[Semantic triple - Wikipedia](https://en.wikipedia.org/wiki/Semantic_triple)  
[Triplestore - Wikipedia](https://en.wikipedia.org/wiki/Triplestore)  
[Named graph - Wikipedia](https://en.wikipedia.org/wiki/Named_graph)  
[Entity–attribute–value model - Wikipedia](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model)  
[Wikidata task force report](https://docs.google.com/document/d/1ZsOyw2sOD3a7xJQ6XCSYDGjZUPxGGl8tuvC7vvtlJRU/edit)
https://en.wikipedia.org/wiki/Semantic_network
https://en.wikipedia.org/wiki/Cognition_Network_Technology
https://en.wikipedia.org/wiki/SNOMED_CT
https://en.wikipedia.org/wiki/Universal_Networking_Language
https://en.wikipedia.org/wiki/Federated_database_system
https://en.wikipedia.org/wiki/IndieWeb
https://github.com/kustomzone/awesome-solid
https://remotestorage.io
https://news.ycombinator.com/item?id=17660131ou
https://hashbase.io
'''

[h-ozzie-gooen]
p-works-on = "n-dex"

[n-list]
p-wikidata-id = "Q12139612"

[n-dex-name-ideas-list]
p-name = "List of ideas for names for DEX"
p-instance-of = "n-list"
p-belongs-to = "n-dex"

[[meta.generators]]
[meta.generators.properties]
p-is-in-list = "n-dex-name-ideas-list"
p-description = "An name idea for DEX. Id is autogenerated, so do not use the ID."
[meta.generators.table]
idPrefix = "dex-name-"
columns = ["p-name", "p-description"]
data = [
    ["DEX", "I like it, but there are a bunch of other DEX-related names out there."],
    ["MetaBase", "Simple, but there are tons of 'base' names out there"],
    ["GitNet", "Somewhat to the point, but instances may not rely on git."],
    ["FactBank Standard", "Could be cool"],
    ["Harmony", "Sounds nice, but some people may not get it."],
    ["Markdata", "There's a company called this."]
]

[n-dex-todo]
p-name = "List of things to do for DEX"
p-instance-of = "n-list"
p-belongs-to = "n-dex"

[p-dex-todo-status]
p-name = "TODO Status"
p-description = "NOT_STARTED, STARTED, ICEBOX, COMPLETED"
p-instance-of = "n-list"
p-belongs-to = "n-dex"

[[meta.generators]]
[meta.generators.properties]
p-is-in-list = "n-dex-todo"
p-description = "Things to do for DEX application"
[meta.generators.table]
idPrefix = "dex-todo-"
columns = ["p-name", "p-dex-todo-status"]
data = [
    ["Convert codebase to TypeScript", "ICEBOX"],
    ["For lists, show tables with all elements", "COMPLETED"],
    ["Values can have subproperties", "COMPLETED"],
    ["Show data about subpackages", "COMPLETED"],
    ["Split up packages, each with simple properties", "NOT_STARTED"],
    ["Make Node Server", "NOT_STARTED"],
    ["Make simple Electron app", "NOT_STARTED"],
    ["Values can have references", "NOT_STARTED"],
    ["Clean up code for Github", "NOT_STARTED"],
    ["References", "NOT_STARTED"],
]