// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Option$Rationale = require("rationale/src/Option.js");

function convertId(f) {
  return /* record */[
          /* id */Option$Rationale.toExn("", f[/* updatedId */5]),
          /* baseId */Option$Rationale.toExn("", f[/* baseId */1]),
          /* isPublic */false
        ];
}

function run(g) {
  return List.map((function (f) {
                var match = f[/* value */3];
                var tmp;
                tmp = match.tag ? /* ThingId */Block.__(1, [Option$Rationale.toExn("Error", match[0][/* updatedId */5])]) : /* String */Block.__(0, [match[0]]);
                return /* record */[
                        /* id */convertId(f[/* thingId */0]),
                        /* subjectId */convertId(f[/* subjectId */1]),
                        /* propertyId */convertId(f[/* propertyId */2]),
                        /* value : record */[/* valueType */tmp]
                      ];
              }), g);
}

exports.convertId = convertId;
exports.run = run;
/* Option-Rationale Not a pure module */
