// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var RList$Rationale = require("rationale/src/RList.js");

function uniqueIds(facts) {
  return RList$Rationale.uniqBy((function (a) {
                return a[/* id */0];
              }), List.flatten(List.map((function (e) {
                        return /* :: */[
                                e[/* id */0],
                                /* :: */[
                                  e[/* subjectId */1],
                                  /* :: */[
                                    e[/* propertyId */2],
                                    /* [] */0
                                  ]
                                ]
                              ];
                      }), facts)));
}

function findType(id, facts) {
  var id$1 = id[/* id */0];
  if (List.exists((function (f) {
            return f[/* id */0][/* id */0] === id$1;
          }), facts)) {
    return /* FACT */0;
  } else {
    return /* ITEM */2;
  }
}

function listFacts(graph) {
  return List.map((function (f) {
                return /* record */[
                        /* thingId */f[/* id */0][/* id */0],
                        /* subjectId */f[/* subjectId */1][/* id */0],
                        /* propertyId */f[/* propertyId */2][/* id */0],
                        /* value */f[/* value */3]
                      ];
              }), graph);
}

function listThings(facts) {
  return List.map((function (id) {
                return /* record */[
                        /* thingId */id[/* id */0],
                        /* idIsPublic */id[/* isPublic */2],
                        /* thingType : Item */0
                      ];
              }), uniqueIds(facts));
}

exports.uniqueIds = uniqueIds;
exports.findType = findType;
exports.listFacts = listFacts;
exports.listThings = listThings;
/* RList-Rationale Not a pure module */
