// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


function factToJs(param) {
  return {
          id: param[/* id */0],
          property: param[/* property */1],
          value: param[/* value */2]
        };
}

function factFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* property */param.property,
          /* value */param.value
        ];
}

function thingToJs(param) {
  return {
          id: param[/* id */0],
          facts: param[/* facts */1],
          templates: param[/* templates */2]
        };
}

function thingFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* facts */param.facts,
          /* templates */param.templates
        ];
}

exports.factToJs = factToJs;
exports.factFromJs = factFromJs;
exports.thingToJs = thingToJs;
exports.thingFromJs = thingFromJs;
/* No side effect */
