[[nouns]]
name = "Foretold"
id = "n2"
description = "The Foretold Website"

[[nouns]]
name = "The Future of Humanity Institute"
id = "n3"

[[nouns]]
name = "The Research Scholars Program"
id = "n4"

[[nouns]]
name = "Organization"
id = "n5"

[[nouns]]
name = "Person"
id = "n6"

[[nouns]]
name = "Project"
id = "n7"

[[properties]]
name = "Works On"
description = "When noun works on things B."
id = "p1"
type = "NOUN"
inverseName = "Worked on by"

[[properties]]
name = "Part of"
id = "p2"
type = "NOUN"
inverseName = "Contains"

[[properties]]
name = "Instance of"
id = "p3"
type = "NOUN"
inverseName = "Instance"

[[properties]]
name = "Wikidata Id"
id = "p4"
type = "STRING"

[[properties]]
name = "Employed By"
id = "p5"
type = "NOUN"
inverseName = "Employs"

[[properties]]
name = "Employed By"
id = "p5"
type = "NOUN"
inverseName = "Employs"

[[properties]]
name = "Is in list"
id = "p6"
type = "NOUN"
inverseName = "Contains"

[[statements]]
nounId = "n1"
propertyId = "p1"
value = "n2"

[[statements]]
nounId = "n4"
propertyId = "p2"
value = "n5"

[[statements]]
nounId = "n1"
propertyId = "p3"
value = "n6"

[[statements]]
nounId = "n3"
propertyId = "p3"
value = "n5"

[[statements]]
nounId = "n3"
propertyId = "p4"
value = "sdflkjsdfkljsd"
[[statements]]
propertyId = "p5"
nounId = "n9"
value = "n3"

#People

[[nouns]]
name = "Nick Bostrom"
id = "n8"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Anders Sandberg"
id = "n9"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Toby Ord"
id = "n10"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Owen Cotton-Barratt"
id = "n11"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Joseph Carlsmith"
id = "n12"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Carl Shulman"
id = "n13"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Owain Evans"
id = "n14"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Stuart Armstrong"
id = "n15"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Ryan Carey"
id = "n16"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Jelena Luketina"
id = "n17"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Carl Shulman"
id = "n18"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Piers Millett"
id = "n19"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Gregory Lewis"
id = "n20"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "Ozzie Gooen"
id = "n1"
[[nouns.statements]]
propertyId = "p5"
value = "n3"

[[nouns]]
name = "An Possible Name for this Website"
id = "n-meta-name-ideas"

[[nouns]]
name = "metabase"
id = "metabase"
[[nouns.statements]]
propertyId = "p6"
value = "n-meta-name-ideas"