// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE


console.log("Hello, BuckleScript and Reason!");

function make(param) {
  console.log("HI!");
  return /* () */0;
}

function foo(param) {
  console.log("HI!!!");
  return 3;
}

export {
  make ,
  foo ,
  
}
/*  Not a pure module */
