// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Graph$Reason = require("../Graph/Graph.bs.js");

function valueToJs(param) {
  return {
          valueType: param[/* valueType */0]
        };
}

function valueFromJs(param) {
  return /* record */[/* valueType */param.valueType];
}

function factToJs(param) {
  return {
          thingId: param[/* thingId */0],
          subjectId: param[/* subjectId */1],
          propertyId: param[/* propertyId */2],
          value: param[/* value */3]
        };
}

function factFromJs(param) {
  return /* record */[
          /* thingId */param.thingId,
          /* subjectId */param.subjectId,
          /* propertyId */param.propertyId,
          /* value */param.value
        ];
}

function thingToJs(param) {
  return {
          thingId: param[/* thingId */0],
          idIsPublic: param[/* idIsPublic */1],
          baseId: param[/* baseId */2],
          thingType: param[/* thingType */3]
        };
}

function thingFromJs(param) {
  return /* record */[
          /* thingId */param.thingId,
          /* idIsPublic */param.idIsPublic,
          /* baseId */param.baseId,
          /* thingType */param.thingType
        ];
}

function showFacts(g) {
  return $$Array.map(factToJs, Js_dict.values(g[/* facts */1]));
}

function showThings(g) {
  return $$Array.map(thingToJs, Js_dict.values(g[/* things */0]));
}

function showValues(g) {
  return $$Array.map(valueToJs, $$Array.map((function (f) {
                    return f[/* value */3];
                  }), Js_dict.values(g[/* facts */1])));
}

function toBase(g) {
  return Graph$Reason.from_facts($$Array.to_list($$Array.map((function (f) {
                        var match = f[/* value */3][/* valueType */0];
                        var tmp;
                        switch (match.tag | 0) {
                          case 0 : 
                          case 1 : 
                              tmp = /* String */Block.__(1, [match[0]]);
                              break;
                          case 2 : 
                              tmp = /* JSON */Block.__(2, [match[0]]);
                              break;
                          
                        }
                        return /* record */[
                                /* id */f[/* thingId */0],
                                /* subjectId */f[/* subjectId */1],
                                /* propertyId */f[/* propertyId */2],
                                /* value */tmp,
                                /* idIsPublic */false,
                                /* baseId */"base25",
                                /* resourceId */"resourceRandom"
                              ];
                      }), Js_dict.values(g[/* facts */1]))));
}

exports.valueToJs = valueToJs;
exports.valueFromJs = valueFromJs;
exports.factToJs = factToJs;
exports.factFromJs = factFromJs;
exports.thingToJs = thingToJs;
exports.thingFromJs = thingFromJs;
exports.showFacts = showFacts;
exports.showThings = showThings;
exports.showValues = showValues;
exports.toBase = toBase;
/* Graph-Reason Not a pure module */
