/* Untyped file generated by genType. */

import * as CreateBucklescriptBlock from 'bs-platform/lib/es6/block.js';

import * as PrimaryGraphBS from './PrimaryGraph.bs';

export const String = function _(Arg1) { return CreateBucklescriptBlock.__(0, [Arg1]) }

export const ThingId = function _(Arg1) { return CreateBucklescriptBlock.__(1, [Arg1]) }

export const JSON = function _(Arg1) { return CreateBucklescriptBlock.__(2, [Arg1]) }

export const Fact = function _(Arg1) { return CreateBucklescriptBlock.__(0, [[Arg1.thingIdString, Arg1.subjectId, Arg1.propertyId, [Arg1.value.valueType]]]) }

export const Item = 0;

export const SUBJECT = 0;

export const PROPERTY = 1;

export const VALUE = 2;

export const Thing_find = function _(Arg1, Arg2) { const result = PrimaryGraphBS.Thing[1](Arg1, Arg2); return (result == null ? result : {thingId:{thingIdString:result[0][0], isPublic:result[0][1], baseId:result[0][2]}, thingType:result[1]}) };

export const Thing_to_json = function _(Arg1) { const result = PrimaryGraphBS.Thing[3]([[Arg1.thingId.thingIdString, Arg1.thingId.isPublic, Arg1.thingId.baseId], Arg1.thingType]); return result };
