// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function factToJs(param) {
  return {
          id: param[/* id */0],
          property: param[/* property */1],
          baseId: param[/* baseId */2],
          resourceId: param[/* resourceId */3],
          value: param[/* value */4]
        };
}

function factFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* property */param.property,
          /* baseId */param.baseId,
          /* resourceId */param.resourceId,
          /* value */param.value
        ];
}

function thingToJs(param) {
  return {
          id: param[/* id */0],
          baseId: param[/* baseId */1],
          resourceId: param[/* resourceId */2],
          facts: param[/* facts */3],
          templates: param[/* templates */4]
        };
}

function thingFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* baseId */param.baseId,
          /* resourceId */param.resourceId,
          /* facts */param.facts,
          /* templates */param.templates
        ];
}

function showFacts(g) {
  return $$Array.map(factToJs, Belt_Array.concatMany($$Array.map((function (r) {
                        return r[/* facts */3];
                      }), g)));
}

exports.factToJs = factToJs;
exports.factFromJs = factFromJs;
exports.thingToJs = thingToJs;
exports.thingFromJs = thingFromJs;
exports.showFacts = showFacts;
/* No side effect */
