// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

var list_to_array = $$Array.of_list;

exports.list_to_array = list_to_array;
/* No side effect */
