imports = [
    "../gitnet-data-base/base/**.toml",
    "../gitnet-data-base/fhi/**.toml",
    "../gitnet-data-base/people-index/*.toml",
    # "../gitnet-data-base/ozzie-personal/**.toml",
]

"output" = "src/data.json"