// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

console.log("Hello, BuckleScript and Reason!");

function hasSubject(subjectId, a) {
  return a[/* subjectId */0] === subjectId;
}

function hasProperty(subjectId, a) {
  return a[/* propertyId */1] === subjectId;
}

var Fact = /* module */[
  /* hasSubject */hasSubject,
  /* hasProperty */hasProperty
];

function withSubject(b, a) {
  return Belt_Array.keep(a, (function (param) {
                return param[/* subjectId */0] === b;
              }));
}

function withProperty(b, a) {
  return Belt_Array.keep(a, (function (param) {
                return param[/* propertyId */1] === b;
              }));
}

function makeThing(id, a) {
  return /* record */[
          /* id */id,
          /* factBank */a
        ];
}

var FactBank = /* module */[
  /* withSubject */withSubject,
  /* withProperty */withProperty,
  /* makeThing */makeThing
];

function properties(a) {
  var __x = withSubject(a[/* id */0], a[/* factBank */1]);
  return Belt_Array.map(__x, (function (e) {
                return e[/* subjectId */0];
              }));
}

var Thing = /* module */[/* properties */properties];

function f(pattern) {
  return pattern + 238 | 0;
}

var bar = 3;

var sdlkfjsdf = "sdfsdf";

exports.Fact = Fact;
exports.FactBank = FactBank;
exports.Thing = Thing;
exports.bar = bar;
exports.sdlkfjsdf = sdlkfjsdf;
exports.f = f;
/*  Not a pure module */
